# users API

###
# baseURL
@baseURL = http://localhost:5000

# Not sure why the VSCode REST Client wont save the cookie automatically
@cookie = Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZDBlODkwNzgtODc2NC00YmI0LWI1YjItYThhZWIxMTcxNDlmIiwiZW1haWwiOiJleGFtcGxlQGdtYWlsLmNvbSIsImlhdCI6MTYxMjMxOTk3OCwiZXhwIjoxNjEyMzIzNTc4fQ.rtUeJ9hbBpReuDHc6cc4zt1wMn9iirUhGvENicBW81U; HttpOnly; Max-Age=3600;,Refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZDBlODkwNzgtODc2NC00YmI0LWI1YjItYThhZWIxMTcxNDlmIiwiZW1haWwiOiJleGFtcGxlQGdtYWlsLmNvbSIsImlhdCI6MTYxMjMxOTk3OCwiZXhwIjoxNjEyOTI0Nzc4fQ.8Zp-VSMB0Jj0Lwe2yigq1jphKBNjMPSh0A1_5km8qG0; HttpOnly; Max-Age=604800;

###
# Login
POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Get All User's Task
GET {{baseURL}}/tasks
Cookie: {{cookie}}

###
# Get All User's Tasks for Today
GET {{baseURL}}/tasks/today
Cookie: {{cookie}}

###
# Find Task By Id
GET {{baseURL}}/tasks/5e219547-2a40-4d83-b193-05386a673e1f
Cookie: {{cookie}}

###
# Add Task
POST {{baseURL}}/tasks
Content-Type: application/json
Cookie: {{cookie}}

{
    "title": "Update something else",
    "userWeight": 5,
    "computedWeight": 5,
    "isDeferred": false,
    "repeatFloor": 2,
    "repeatCeiling": 2,
    "lastCompletedDt": "2021-01-01T00:00:00.001Z",
    "lastDeferredDt": "2021-01-01T00:00:00.001Z"
}


###
# Delete Task
DELETE {{baseURL}}/tasks/a7554683-b8a3-47b9-8ecd-7c89732660e8
Cookie: {{cookie}}


###
# Update Task
PUT {{baseURL}}/tasks/0d52313a-88a6-4eed-a43a-4ea2a3dbac0c
Content-Type: application/json
Cookie: {{cookie}}

{
    "title": "Update something else",
    "userWeight": 50,
    "computedWeight": 50,
    "isDeferred": false,
    "repeatFloor": 2,
    "repeatCeiling": 2,
    "lastCompletedDt": "2021-01-31T00:00:00.00Z",
    "lastDeferredDt": "2021-01-01T00:00:00.001Z"
}

###
# Defer Task
PUT {{baseURL}}/tasks/defer/0d52313a-88a6-4eed-a43a-4ea2a3dbac0c
Cookie: {{cookie}}


###
# Complete Task
PUT {{baseURL}}/tasks/complete/0d52313a-88a6-4eed-a43a-4ea2a3dbac0c
Cookie: {{cookie}}

