# users API

###
# baseURL
@baseURL = http://localhost:5000

# Not sure why the VSCode REST Client wont save the cookie automatically
@cookie = Authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZTBiMzg1NTItZmEwNy00ZTljLWI0YWUtY2IwMWY0Yzk3MTQ1IiwiZW1haWwiOiJleGFtcGxlQGdtYWlsLmNvbSIsImlhdCI6MTYxMjQxNDU2NSwiZXhwIjoxNjEyNDE4MTY1fQ.5mBcOFrSEu_U7wI5oaSOWjSEjUrE9uAI1Cx4LAmUvoA; HttpOnly; Max-Age=3600;,Refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiZTBiMzg1NTItZmEwNy00ZTljLWI0YWUtY2IwMWY0Yzk3MTQ1IiwiZW1haWwiOiJleGFtcGxlQGdtYWlsLmNvbSIsImlhdCI6MTYxMjQxNDU2NiwiZXhwIjoxNjEzMDE5MzY2fQ.VsY0ct1HnOMiGRVkHfaA5K-I3IS29b7SHlcmsC6hh-U; HttpOnly; Max-Age=604800;

###
# Login
POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "example@gmail.com",
	"password": "qwer1234"
}

###
# Get All User's Task
GET {{baseURL}}/tasks
Cookie: {{cookie}}

###
# Get All User's Tasks for Today
GET {{baseURL}}/tasks/today
Cookie: {{cookie}}

###
# Find Task By Id
GET {{baseURL}}/tasks/5e219547-2a40-4d83-b193-05386a673e1f
Cookie: {{cookie}}

###
# Add Task
POST {{baseURL}}/tasks
Content-Type: application/json
Cookie: {{cookie}}

{
    "title": "Update something else",
    "userWeight": 50,
    "computedWeight": 60,
    "isDeferred": true,
    "repeatFloor": 2,
    "repeatCeiling": 2,
    "lastCompletedDt": "2021-01-31T00:00:00.000Z",
    "lastDeferredDt": "2021-02-03T01:12:40.208Z"
}


###
# Delete Task
DELETE {{baseURL}}/tasks/a7554683-b8a3-47b9-8ecd-7c89732660e8
Cookie: {{cookie}}


###
# Update Task
PUT {{baseURL}}/tasks/7c6b034d-0566-4d58-bd2c-1922ed036227
Content-Type: application/json
Cookie: {{cookie}}

{
    "taskId": "7c6b034d-0566-4d58-bd2c-1922ed036227",
    "title": "Update something else",
    "userWeight": 50,
    "computedWeight": 60,
    "isDeferred": true,
    "repeatFloor": 2,
    "repeatCeiling": 2,
    "lastCompletedDt": "2021-01-31T00:00:00.000Z",
    "lastDeferredDt": "2021-02-03T01:12:40.208Z"
}

###
# Defer Task
PUT {{baseURL}}/tasks/defer/7c6b034d-0566-4d58-bd2c-1922ed036227
Content-Type: application/json
Cookie: {{cookie}}


###
# Complete Task
PUT {{baseURL}}/tasks/complete/7c6b034d-0566-4d58-bd2c-1922ed036227
Cookie: {{cookie}}

